# Generated by Django 5.2.7 on 2026-07-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0030_remove_courseconfig_homepage_demo_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBlockCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('blocks', models.ManyToManyField(blank=True, related_name='collections', to='standalone.courseblock')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_collections', to='standalone.course')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('course', 'title'), name='unique_course_block_collection_title')],
            },
        ),
    ]
