# Generated by Django 5.2.7 on 2026-07-06 11:38

import standalone.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0031_courseblockcollection'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseblock',
            name='avatar_file',
            field=models.FileField(blank=True, upload_to=standalone.models.course_block_avatar_upload_to),
        ),
        migrations.AddField(
            model_name='courseblock',
            name='avatar_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courseblock',
            name='avatar_generation_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='courseblock',
            name='avatar_generation_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='idle', max_length=20),
        ),
    ]
