# Generated by Django 5.2.7 on 2026-07-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standalone", "0032_courseblock_avatar_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbankitem",
            name="math_metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
