# Generated by Django 5.2.7 on 2026-07-15 16:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0036_disable_builder_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='blockconfig',
            name='coverage_factor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='courseconfig',
            name='coverage_factor',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
