# Generated by Django 5.2.7 on 2026-07-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standalone", "0037_blockconfig_coverage_factor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseconfig",
            name="calculator_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
