# Generated by Django 5.2.7 on 2026-07-18 21:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standalone', '0039_blockresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasUserIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas_user_id', models.PositiveBigIntegerField(unique=True)),
                ('login_id_hash', models.CharField(db_index=True, max_length=64)),
                ('sortable_name', models.CharField(blank=True, max_length=255)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('search_text', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['sortable_name', 'display_name', 'canvas_user_id'],
            },
        ),
        migrations.CreateModel(
            name='CanvasCourseLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas_course_id', models.PositiveBigIntegerField(unique=True)),
                ('canvas_course_name', models.CharField(blank=True, max_length=255)),
                ('allowed_iframe_origin', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_links', to='standalone.course')),
            ],
            options={
                'ordering': ['course__title', 'canvas_course_id'],
            },
        ),
        migrations.CreateModel(
            name='CanvasCourseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canvas_role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('ta', 'Teaching assistant'), ('designer', 'Designer')], max_length=20)),
                ('enrollment_state', models.CharField(default='active', max_length=30)),
                ('practice_state', models.JSONField(blank=True, default=dict)),
                ('canvas_course_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='standalone.canvascourselink')),
                ('canvas_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_memberships', to='standalone.canvasuseridentity')),
            ],
            options={
                'ordering': ['canvas_course_link__canvas_course_id', 'canvas_user__sortable_name', 'canvas_user__display_name'],
                'unique_together': {('canvas_course_link', 'canvas_user')},
            },
        ),
        migrations.CreateModel(
            name='CanvasMagicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('sent_canvas_message_id', models.CharField(blank=True, max_length=100)),
                ('sent_canvas_subject', models.CharField(blank=True, max_length=255)),
                ('sent_to_canvas_user_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='magic_links', to='standalone.canvascoursemembership')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
